<?php
return array (
  101 => 
  array (
    'id' => 101,
    'name' => '首页',
    'parentid' => 0,
    'm' => 'admin',
    'c' => 'index',
    'a' => 'init',
    'data' => '',
    'listorder' => 0,
    'display' => '1',
    'project1' => 1,
    'project2' => 1,
    'project3' => 1,
    'project4' => 1,
    'project5' => 1,
    'type' => 1,
    'status' => 1,
    'update_time' => '2019-05-22 16:00:00',
    'icon' => 'home',
    'path' => '?m=admin&c=index&a=init&menu_id=101',
    '_level' => 1,
    'children' => 
    array (
      201 => 
      array (
        'id' => 201,
        'name' => '问答',
        'parentid' => 101,
        'm' => 'content',
        'c' => 'wenwen',
        'a' => '',
        'data' => '',
        'listorder' => 0,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => '2019-06-03 17:05:49',
        'icon' => '',
        'path' => '?m=content&c=wenwen&a=&menu_id=201',
        '_level' => 2,
        'children' => 
        array (
          301 => 
          array (
            'id' => 301,
            'name' => '问题管理',
            'parentid' => 201,
            'm' => 'content',
            'c' => 'wenwen',
            'a' => 'init',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => '2019-06-03 17:05:48',
            'icon' => '',
            'path' => '?m=content&c=wenwen&a=init&menu_id=301',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          302 => 
          array (
            'id' => 302,
            'name' => '解答管理',
            'parentid' => 201,
            'm' => 'content',
            'c' => 'wenwen',
            'a' => 'managepost',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => '2019-05-23 16:25:34',
            'icon' => '',
            'path' => '?m=content&c=wenwen&a=managepost&menu_id=302',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      202 => 
      array (
        'id' => 202,
        'name' => '资讯',
        'parentid' => 101,
        'm' => 'content',
        'c' => 'content',
        'a' => '',
        'data' => '',
        'listorder' => 1,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=content&c=content&a=&menu_id=202',
        '_level' => 2,
        'children' => 
        array (
          303 => 
          array (
            'id' => 303,
            'name' => '热点资讯',
            'parentid' => 202,
            'm' => 'admin',
            'c' => 'position',
            'a' => 'public_item',
            'data' => 'posid=18',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=position&a=public_item&menu_id=303&posid=18',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          304 => 
          array (
            'id' => 304,
            'name' => '各地蜂情',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=102',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=304&catid=102',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          305 => 
          array (
            'id' => 305,
            'name' => '政策法规',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=103',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=305&catid=103',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          306 => 
          array (
            'id' => 306,
            'name' => '行业动态',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=104',
            'listorder' => 3,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=306&catid=104',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          307 => 
          array (
            'id' => 307,
            'name' => '国际蜂情',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=105',
            'listorder' => 4,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=307&catid=105',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          308 => 
          array (
            'id' => 308,
            'name' => '技术发展',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=106',
            'listorder' => 5,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=308&catid=106',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          309 => 
          array (
            'id' => 309,
            'name' => '协会服务',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=107',
            'listorder' => 6,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=309&catid=107',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          310 => 
          array (
            'id' => 310,
            'name' => '行业会议',
            'parentid' => 202,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=108',
            'listorder' => 7,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=310&catid=108',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          311 => 
          array (
            'id' => 311,
            'name' => '省份设置',
            'parentid' => 202,
            'm' => 'admin',
            'c' => 'linkage',
            'a' => 'public_manage_submenu',
            'data' => 'keyid=1',
            'listorder' => 8,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=linkage&a=public_manage_submenu&menu_id=311&keyid=1',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      203 => 
      array (
        'id' => 203,
        'name' => '课程',
        'parentid' => 101,
        'm' => 'content',
        'c' => 'keshi',
        'a' => '',
        'data' => '',
        'listorder' => 2,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=content&c=keshi&a=&menu_id=203',
        '_level' => 2,
        'children' => 
        array (
          312 => 
          array (
            'id' => 312,
            'name' => '课时管理',
            'parentid' => 203,
            'm' => 'content',
            'c' => 'content',
            'a' => 'init',
            'data' => 'catid=109&from=train',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=init&menu_id=312&catid=109&from=train',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          313 => 
          array (
            'id' => 313,
            'name' => '目录管理',
            'parentid' => 203,
            'm' => 'admin',
            'c' => 'linkage',
            'a' => 'public_manage_submenu',
            'data' => 'keyid=3364',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=linkage&a=public_manage_submenu&menu_id=313&keyid=3364',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          314 => 
          array (
            'id' => 314,
            'name' => '课时评论',
            'parentid' => 203,
            'm' => 'comment',
            'c' => 'comment_admin',
            'a' => 'listinfo',
            'data' => '',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=comment&c=comment_admin&a=listinfo&menu_id=314',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      204 => 
      array (
        'id' => 204,
        'name' => '用户',
        'parentid' => 101,
        'm' => 'member',
        'c' => 'member',
        'a' => '',
        'data' => '',
        'listorder' => 3,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=member&c=member&a=&menu_id=204',
        '_level' => 2,
        'children' => 
        array (
          315 => 
          array (
            'id' => 315,
            'name' => '用户管理',
            'parentid' => 204,
            'm' => 'member',
            'c' => 'member',
            'a' => 'manage',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=member&c=member&a=manage&menu_id=315',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          316 => 
          array (
            'id' => 316,
            'name' => '专家库',
            'parentid' => 204,
            'm' => 'member',
            'c' => 'member',
            'a' => 'expertmanage',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=member&c=member&a=expertmanage&menu_id=316',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          317 => 
          array (
            'id' => 317,
            'name' => '审核专家申请',
            'parentid' => 204,
            'm' => 'member',
            'c' => 'member_verify',
            'a' => 'manage',
            'data' => '',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=member&c=member_verify&a=manage&menu_id=317',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          318 => 
          array (
            'id' => 318,
            'name' => '管理用户组',
            'parentid' => 204,
            'm' => 'member',
            'c' => 'member_group',
            'a' => 'manage',
            'data' => '',
            'listorder' => 3,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=member&c=member_group&a=manage&menu_id=318',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          319 => 
          array (
            'id' => 319,
            'name' => '用户擅长选项',
            'parentid' => 204,
            'm' => 'member',
            'c' => 'member_wenwenmodule',
            'a' => 'manage',
            'data' => '',
            'listorder' => 4,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=member&c=member_wenwenmodule&a=manage&menu_id=319',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      205 => 
      array (
        'id' => 205,
        'name' => '消息',
        'parentid' => 101,
        'm' => 'chat',
        'c' => 'group',
        'a' => '',
        'data' => '',
        'listorder' => 4,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=chat&c=group&a=&menu_id=205',
        '_level' => 2,
        'children' => 
        array (
          320 => 
          array (
            'id' => 320,
            'name' => '群管理',
            'parentid' => 205,
            'm' => 'chat',
            'c' => 'group',
            'a' => 'init',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=chat&c=group&a=init&menu_id=320',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          321 => 
          array (
            'id' => 321,
            'name' => '群日志管理',
            'parentid' => 205,
            'm' => 'chat',
            'c' => 'group_log',
            'a' => 'init',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=chat&c=group_log&a=init&menu_id=321',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          322 => 
          array (
            'id' => 322,
            'name' => '审核群',
            'parentid' => 205,
            'm' => 'chat',
            'c' => 'group_check',
            'a' => 'init',
            'data' => '',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=chat&c=group_check&a=init&menu_id=322',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          323 => 
          array (
            'id' => 323,
            'name' => '群设置',
            'parentid' => 205,
            'm' => 'chat',
            'c' => 'group_setting',
            'a' => 'init',
            'data' => '',
            'listorder' => 3,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=chat&c=group_setting&a=init&menu_id=323',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          324 => 
          array (
            'id' => 324,
            'name' => '蜂博士团队管理',
            'parentid' => 205,
            'm' => 'chat',
            'c' => 'group_support',
            'a' => 'init',
            'data' => '',
            'listorder' => 4,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=chat&c=group_support&a=init&menu_id=324',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      206 => 
      array (
        'id' => 206,
        'name' => 'APP设置',
        'parentid' => 101,
        'm' => 'admin',
        'c' => 'position',
        'a' => '',
        'data' => '',
        'listorder' => 5,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=admin&c=position&a=&menu_id=206',
        '_level' => 2,
        'children' => 
        array (
          325 => 
          array (
            'id' => 325,
            'name' => 'app banner管理',
            'parentid' => 206,
            'm' => 'admin',
            'c' => 'position',
            'a' => 'public_item',
            'data' => 'posid=19&menuid=32',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=position&a=public_item&menu_id=325&posid=19&menuid=32',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          326 => 
          array (
            'id' => 326,
            'name' => '用户协议',
            'parentid' => 206,
            'm' => 'content',
            'c' => 'content',
            'a' => 'add',
            'data' => 'catid=2',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=add&menu_id=326&catid=2',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          327 => 
          array (
            'id' => 327,
            'name' => '关于蜂博士',
            'parentid' => 206,
            'm' => 'content',
            'c' => 'content',
            'a' => 'add',
            'data' => 'catid=3',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=content&a=add&menu_id=327&catid=3',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          328 => 
          array (
            'id' => 328,
            'name' => '视频广告',
            'parentid' => 206,
            'm' => 'admin',
            'c' => 'video',
            'a' => 'init',
            'data' => 'catid=124',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=video&a=init&menu_id=328&catid=124',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
    ),
  ),
  102 => 
  array (
    'id' => 102,
    'name' => '设置',
    'parentid' => 0,
    'm' => 'admin',
    'c' => 'menu',
    'a' => 'child',
    'data' => 'menuid=102',
    'listorder' => 1,
    'display' => '1',
    'project1' => 1,
    'project2' => 1,
    'project3' => 1,
    'project4' => 1,
    'project5' => 1,
    'type' => 1,
    'status' => 1,
    'update_time' => '2019-05-22 16:00:02',
    'icon' => 'cogs',
    'path' => '?m=admin&c=menu&a=child&menu_id=102&menuid=102',
    '_level' => 1,
    'children' => 
    array (
      207 => 
      array (
        'id' => 207,
        'name' => '内容设置',
        'parentid' => 102,
        'm' => 'admin',
        'c' => 'category',
        'a' => '',
        'data' => '',
        'listorder' => 4,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 2,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=admin&c=category&a=&menu_id=207',
        '_level' => 2,
        'children' => 
        array (
          329 => 
          array (
            'id' => 329,
            'name' => '管理栏目',
            'parentid' => 207,
            'm' => 'admin',
            'c' => 'category',
            'a' => 'init',
            'data' => 'module=admin',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=category&a=init&menu_id=329&module=admin',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          330 => 
          array (
            'id' => 330,
            'name' => '模型管理',
            'parentid' => 207,
            'm' => 'content',
            'c' => 'sitemodel',
            'a' => 'init',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=sitemodel&a=init&menu_id=330',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          331 => 
          array (
            'id' => 331,
            'name' => '批量更新url',
            'parentid' => 207,
            'm' => 'content',
            'c' => 'create_html',
            'a' => 'update_urls',
            'data' => '',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=content&c=create_html&a=update_urls&menu_id=331',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      208 => 
      array (
        'id' => 208,
        'name' => '相关设置',
        'parentid' => 102,
        'm' => 'admin',
        'c' => 'setting',
        'a' => '',
        'data' => '',
        'listorder' => 5,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 2,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=admin&c=setting&a=&menu_id=208',
        '_level' => 2,
        'children' => 
        array (
          332 => 
          array (
            'id' => 332,
            'name' => '站点管理',
            'parentid' => 208,
            'm' => 'admin',
            'c' => 'site',
            'a' => 'init',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=site&a=init&menu_id=332',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          333 => 
          array (
            'id' => 333,
            'name' => '基本设置',
            'parentid' => 208,
            'm' => 'admin',
            'c' => 'setting',
            'a' => 'init',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=setting&a=init&menu_id=333',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          338 => 
          array (
            'id' => 338,
            'name' => '菜单设置',
            'parentid' => 208,
            'm' => 'admin',
            'c' => 'menu_setting',
            'a' => 'init',
            'data' => '',
            'listorder' => 2,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=menu_setting&a=init&menu_id=338',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      209 => 
      array (
        'id' => 209,
        'name' => '管理员设置',
        'parentid' => 102,
        'm' => 'admin',
        'c' => 'manage',
        'a' => '',
        'data' => '',
        'listorder' => 6,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 2,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=admin&c=manage&a=&menu_id=209',
        '_level' => 2,
        'children' => 
        array (
          334 => 
          array (
            'id' => 334,
            'name' => '管理员管理',
            'parentid' => 209,
            'm' => 'admin',
            'c' => 'admin_manage',
            'a' => 'init',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=admin_manage&a=init&menu_id=334',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          335 => 
          array (
            'id' => 335,
            'name' => '角色管理',
            'parentid' => 209,
            'm' => 'admin',
            'c' => 'role',
            'a' => 'init',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 2,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=role&a=init&menu_id=335',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
      210 => 
      array (
        'id' => 210,
        'name' => '帐号管理',
        'parentid' => 102,
        'm' => 'admin',
        'c' => 'info',
        'a' => '',
        'data' => '',
        'listorder' => 7,
        'display' => '1',
        'project1' => 1,
        'project2' => 1,
        'project3' => 1,
        'project4' => 1,
        'project5' => 1,
        'type' => 1,
        'status' => 1,
        'update_time' => NULL,
        'icon' => '',
        'path' => '?m=admin&c=info&a=&menu_id=210',
        '_level' => 2,
        'children' => 
        array (
          336 => 
          array (
            'id' => 336,
            'name' => '修改个人信息',
            'parentid' => 210,
            'm' => 'admin',
            'c' => 'admin_manage',
            'a' => 'public_edit_info',
            'data' => '',
            'listorder' => 0,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=admin_manage&a=public_edit_info&menu_id=336',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
          337 => 
          array (
            'id' => 337,
            'name' => '修改密码',
            'parentid' => 210,
            'm' => 'admin',
            'c' => 'admin_manage',
            'a' => 'public_edit_pwd',
            'data' => '',
            'listorder' => 1,
            'display' => '1',
            'project1' => 1,
            'project2' => 1,
            'project3' => 1,
            'project4' => 1,
            'project5' => 1,
            'type' => 1,
            'status' => 1,
            'update_time' => NULL,
            'icon' => '',
            'path' => '?m=admin&c=admin_manage&a=public_edit_pwd&menu_id=337',
            '_level' => 3,
            'children' => 
            array (
            ),
          ),
        ),
      ),
    ),
  ),
);
?>