<?php
return array (
  1 => 
  array (
    'groupid' => '1',
    'name' => '普通用户',
    'issystem' => '1',
    'starnum' => '2',
    'point' => '100',
    'allowmessage' => '150',
    'allowvisit' => '0',
    'allowpost' => '1',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '1',
    'allowsendmessage' => '1',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '300.00',
    'price_m' => '30.00',
    'price_d' => '1.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '',
    'sort' => '1',
    'disabled' => '0',
  ),
  9 => 
  array (
    'groupid' => '9',
    'name' => '企业专家',
    'issystem' => '0',
    'starnum' => '50',
    'point' => '100',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '3',
    'disabled' => '0',
  ),
  10 => 
  array (
    'groupid' => '10',
    'name' => '教研专家',
    'issystem' => '0',
    'starnum' => '20',
    'point' => '200',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '3',
    'sort' => '2',
    'disabled' => '0',
  ),
  11 => 
  array (
    'groupid' => '11',
    'name' => '民间专家',
    'issystem' => '0',
    'starnum' => '30',
    'point' => '300',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '4',
    'disabled' => '0',
  ),
);
?>