<?php
return array (
  'title' => '课程视频分类',
  'style' => '2',
  'image' => '',
  'siteid' => '1',
  'data' => 
  array (
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '蜂群选购蜂群选购蜂群选购蜂群选购蜂群选购蜂群选购蜂群选购蜂群',
      'style' => '0',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3370,3420,3436,3437,3438,3439,3440,3441,3442,3443',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
      'image' => 'http://test.hibeeok.com/uploadfile/2018/0806/20180806015640232.png',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '养蜂装备',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3371,3421',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '场地选择',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3372,3422',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '蜂箱排列',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3373,3446',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '蜂群检查',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3374,3444',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '蜜蜂营养',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3375,3445',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '蜂群分合',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '防止盗蜂',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '早春繁殖',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '蜂群越冬',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3379,3454',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '中蜂养殖',
      'style' => '',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3381,3408,3409,3410,3411,3412',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '人工育王',
      'style' => '0',
      'parentid' => '3368',
      'child' => '1',
      'arrchildid' => '3392,3455,3456,3457',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
      'image' => 'http://test.hibeeok.com/uploadfile/2018/0815/20180815094320786.jpg',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '培育强群',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '转地养蜂',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '王浆生产',
      'style' => '0',
      'parentid' => '3368',
      'child' => '1',
      'arrchildid' => '3395,3450,3451,3452,3453',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
      'image' => '',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '蜂花粉生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '蜂蜜生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '蜂胶生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '蜂毒生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '雄蜂蛹生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '蜂蜡生产',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '农药中毒',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3402',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '甘露蜜中毒',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '花蜜中毒',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '其他关注',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '蜜蜂的起源与进化',
      'style' => '0',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => 'http://g.bee.nzsoso.com/uploadfile/2018/0502/20180502040757394.jpg',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '蜜蜂分类',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '中蜂特点',
      'style' => '',
      'parentid' => '3381',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '中蜂过箱',
      'style' => '',
      'parentid' => '3381',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '中蜂饲养',
      'style' => '',
      'parentid' => '3381',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '中蜂管理',
      'style' => '',
      'parentid' => '3381',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '中蜂病虫害',
      'style' => '',
      'parentid' => '3381',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '蜜蜂',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '蜜蜂',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '蜜蜂2',
      'style' => '0',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => '',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '蜂群1',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '测试页-无视频和音频',
      'style' => '',
      'parentid' => '3371',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '蜜蜂1',
      'style' => '',
      'parentid' => '3372',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '蜜蜂3',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '蜜蜂6',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '蜜蜂7',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '蜜蜂8',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '蜜蜂9',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '蜜蜂10',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '蜜蜂11',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '蜜蜂13',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '蜜蜂14',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '蜜蜂15',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '1',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '2',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '3',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '4',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '5',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '6',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '7',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3442',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '8',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '蜂群检查1',
      'style' => '',
      'parentid' => '3374',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => 'mifyy',
      'style' => '',
      'parentid' => '3375',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3446 => 
    array (
      'linkageid' => '3446',
      'name' => '上传',
      'style' => '',
      'parentid' => '3373',
      'child' => '0',
      'arrchildid' => '3446',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3448 => 
    array (
      'linkageid' => '3448',
      'name' => '20180808',
      'style' => '0',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3448,3449',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '1',
      'image' => 'http://test.hibeeok.com/uploadfile/2018/0808/20180808101200295.jpg',
    ),
    3449 => 
    array (
      'linkageid' => '3449',
      'name' => '9点50',
      'style' => '',
      'parentid' => '3448',
      'child' => '0',
      'arrchildid' => '3449',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3450 => 
    array (
      'linkageid' => '3450',
      'name' => '蜂群安全越冬',
      'style' => '',
      'parentid' => '3395',
      'child' => '0',
      'arrchildid' => '3450',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3451 => 
    array (
      'linkageid' => '3451',
      'name' => '加速蜂群春繁',
      'style' => '',
      'parentid' => '3395',
      'child' => '0',
      'arrchildid' => '3451',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3452 => 
    array (
      'linkageid' => '3452',
      'name' => '选育良种育优质蜂王',
      'style' => '',
      'parentid' => '3395',
      'child' => '0',
      'arrchildid' => '3452',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3453 => 
    array (
      'linkageid' => '3453',
      'name' => '培育和保持强群',
      'style' => '',
      'parentid' => '3395',
      'child' => '0',
      'arrchildid' => '3453',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3454 => 
    array (
      'linkageid' => '3454',
      'name' => '蜂群越冬',
      'style' => '',
      'parentid' => '3379',
      'child' => '0',
      'arrchildid' => '3454',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3455 => 
    array (
      'linkageid' => '3455',
      'name' => '育王的时间和条件',
      'style' => '',
      'parentid' => '3392',
      'child' => '0',
      'arrchildid' => '3455',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3456 => 
    array (
      'linkageid' => '3456',
      'name' => '育王的计划和记录',
      'style' => '',
      'parentid' => '3392',
      'child' => '0',
      'arrchildid' => '3456',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3457 => 
    array (
      'linkageid' => '3457',
      'name' => '利用蜂群的组织',
      'style' => '',
      'parentid' => '3392',
      'child' => '0',
      'arrchildid' => '3457',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3458 => 
    array (
      'linkageid' => '3458',
      'name' => '1',
      'style' => '',
      'parentid' => '3367',
      'child' => '1',
      'arrchildid' => '3458,3459',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3459 => 
    array (
      'linkageid' => '3459',
      'name' => '1-1',
      'style' => '',
      'parentid' => '3458',
      'child' => '0',
      'arrchildid' => '3459',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3460 => 
    array (
      'linkageid' => '3460',
      'name' => '2',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3460',
      'keyid' => '3364',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '初级',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3366,3370,3420,3436,3437,3438,3439,3440,3441,3442,3443,3371,3421,3372,3422,3373,3446,3374,3444,3375,3445,3376,3377,3378,3379,3454,3381,3408,3409,3410,3411,3412,3448,3449,3380,3369,3406,3407,3414,3415,3423,3426,3427,3428,3429,3430,3431,3433,3434,3435,3424,3425,3432',
      'keyid' => '3364',
      'listorder' => '1',
      'description' => '静态无病害养殖管理',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => '',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '其他关注',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3364',
      'listorder' => '1',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '蜜蜂4',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3364',
      'listorder' => '1',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '中级',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3367,3458,3459,3460',
      'keyid' => '3364',
      'listorder' => '2',
      'description' => '蜜蜂病虫害',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => '',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '蜜蜂生物学',
      'style' => '0',
      'parentid' => '3366',
      'child' => '1',
      'arrchildid' => '3369,3406,3407,3414,3415,3423,3426,3427,3428,3429,3430,3431,3433,3434,3435,3424,3425,3432',
      'keyid' => '3364',
      'listorder' => '2',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => 'http://g.bee.nzsoso.com/uploadfile/2018/0502/20180502040757394.jpg',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '蜜蜂5',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3364',
      'listorder' => '2',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '蜜蜂12',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3364',
      'listorder' => '2',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'image' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '高级',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3368,3392,3455,3456,3457,3393,3394,3395,3450,3451,3452,3453,3396,3397,3398,3399,3400,3401,3402,3403,3404,3405',
      'keyid' => '3364',
      'listorder' => '3',
      'description' => '',
      'setting' => '{"level":"0"}',
      'siteid' => '0',
      'image' => '',
    ),
  ),
);
?>