<?php
return array (
  18 => 
  array (
    'id' => '18',
    'catid' => '102',
    'typeid' => '0',
    'title' => '人工养蜂重在繁育管理，嗯嗯恩恩嗯嗯嗯',
    'style' => '',
    'thumb' => 'http://g.bee.nzsoso.com/uploadfile/2018/0426/1524712035792635.jpg',
    'keywords' => '',
    'description' => '蜂蜜是一种营养丰富的天然滋养食品，含有多种无机盐、维生素和有益人体健康的微量元素，蜂王浆更是高级营养品。蜜蜂除了提供蜂蜜、蜂王浆、   ',
    'posids' => '1',
    'url' => 'http://g.bee.nzsoso.com/index.php?m=content&c=index&a=show&catid=102&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'test',
    'inputtime' => '1524711434',
    'updatetime' => '1526977346',
    'area' => '',
    'hitsid' => 'c-1-18',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '102',
    'typeid' => '0',
    'title' => '慈溪：养蜂产业面临断代隐忧',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　春日里油菜花盛放，养蜂人也迎来了今年第一次花期&mdash;&mdash;油菜花季。随后的半年时间里，养蜂人就要开始循着花香的足迹往北追赶花期、放养蜂群   ',
    'posids' => '1',
    'url' => 'http://localhost/index.php?m=content&c=index&a=show&catid=102&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'iamjscxy',
    'inputtime' => '1524536210',
    'updatetime' => '1524445125',
    'area' => '13',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>