<?php
return array (
  5 => 
  array (
    'id' => '5',
    'catid' => '109',
    'typeid' => '0',
    'title' => '蜜蜂的起源与进化章节',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '是',
    'posids' => '0',
    'url' => 'http://g.bee.nzsoso.com/index.php?m=content&c=index&a=show&catid=109&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'iamjscxy',
    'inputtime' => '1524029584',
    'updatetime' => '1525231066',
    'beevlist' => NULL,
    'beetype' => '3406',
    'bee_video' => 'cce50b4fd7c020e9be71e830d4a32a86_c',
    'hitsid' => 'c-16-5',
    'views' => '21',
    'yesterdayviews' => '0',
    'dayviews' => '20',
    'weekviews' => '20',
    'monthviews' => '20',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '109',
    'typeid' => '0',
    'title' => '蜜蜂的进化过程',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '蜜蜂的进化过程',
    'posids' => '0',
    'url' => 'http://g.bee.nzsoso.com/index.php?m=content&c=index&a=show&catid=109&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'test',
    'inputtime' => '1524898434',
    'updatetime' => '1525225454',
    'beevlist' => NULL,
    'beetype' => '3406',
    'bee_video' => '',
    'hitsid' => 'c-16-8',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '109',
    'typeid' => '0',
    'title' => '蜂群选购概述',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '蜂群选购概述',
    'posids' => '0',
    'url' => 'http://g.bee.nzsoso.com/index.php?m=content&c=index&a=show&catid=109&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'test',
    'inputtime' => '1524898105',
    'updatetime' => '1524898174',
    'beevlist' => NULL,
    'beetype' => '3370',
    'bee_video' => '',
    'hitsid' => 'c-16-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '109',
    'typeid' => '0',
    'title' => '蜜蜂分类概述',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '蜜蜂分类概述',
    'posids' => '0',
    'url' => 'http://g.bee.nzsoso.com/index.php?m=content&c=index&a=show&catid=109&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'test',
    'inputtime' => '1524898255',
    'updatetime' => '1524898286',
    'beevlist' => NULL,
    'beetype' => '3407',
    'bee_video' => '',
    'hitsid' => 'c-16-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>