<?php
return array (
  'admin' => 
  array (
    'module' => 'admin',
    'name' => 'admin',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"admin_email":"405579125@qq.com","maxloginfailedtimes":"8","minrefreshtime":"2","mail_type":"1","mail_server":"smtp.qq.com","mail_port":"25","category_ajax":"0","mail_user":"405579125@qq.com","mail_auth":"1","mail_from":"405579125@qq.com","mail_password":"","errorlog_size":"20"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-18',
    'updatedate' => '2010-10-18',
  ),
  'member' => 
  array (
    'module' => 'member',
    'name' => '会员',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"allowregister":"1","choosemodel":"1","enablemailcheck":"0","enablcodecheck":"0","mobile_checktype":"0","user_sendsms_title":"","registerverify":"1","showapppoint":"0","rmb_point_rate":"10","defualtpoint":"0","defualtamount":"0","showregprotocol":"0","regprotocol":"\\u8bf7\\u4ed4\\u7ec6\\u9605\\u8bfb\\u4e0b\\u9762\\u7684\\u534f\\u8bae\\uff0c\\u53ea\\u6709\\u63a5\\u53d7\\u534f\\u8bae\\u624d\\u80fd\\u7ee7\\u7eed\\u8fdb\\u884c\\u6ce8\\u518c\\u3002 ","registerverifymessage":"\\u60a8\\u7684\\u8d26\\u53f7\\u9700\\u8981\\u90ae\\u7bb1\\u8ba4\\u8bc1\\uff0c\\u70b9\\u51fb\\u4e0b\\u9762\\u94fe\\u63a5\\u8fdb\\u884c\\u8ba4\\u8bc1\\uff1a{click}\\r\\n\\u6216\\u8005\\u5c06\\u7f51\\u5740\\u590d\\u5236\\u5230\\u6d4f\\u89c8\\u5668\\uff1a{url}","forgetpassword":"\\u5bc6\\u7801\\u627e\\u56de\\uff0c\\u8bf7\\u5728\\u4e00\\u5c0f\\u65f6\\u5185\\u70b9\\u51fb\\u4e0b\\u9762\\u94fe\\u63a5\\u8fdb\\u884c\\u64cd\\u4f5c\\uff1a{click}\\r\\n\\u6216\\u8005\\u5c06\\u7f51\\u5740\\u590d\\u5236\\u5230\\u6d4f\\u89c8\\u5668\\uff1a{url}"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'pay' => 
  array (
    'module' => 'pay',
    'name' => '支付',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'digg' => 
  array (
    'module' => 'digg',
    'name' => '顶一下',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'special' => 
  array (
    'module' => 'special',
    'name' => '专题',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'content' => 
  array (
    'module' => 'content',
    'name' => '内容模块',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'search' => 
  array (
    'module' => 'search',
    'name' => '全站搜索',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"fulltextenble":"1","relationenble":"1","suggestenable":"1","sphinxenable":"0","sphinxhost":"10.228.134.102","sphinxport":"9312","1":{"fulltextenble":"1","relationenble":"0","suggestenable":"0","sphinxenable":"1","sphinxhost":"","sphinxport":""}}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'scan' => 
  array (
    'module' => 'scan',
    'name' => '木马扫描',
    'url' => 'scan',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'attachment' => 
  array (
    'module' => 'attachment',
    'name' => '附件',
    'url' => 'attachment',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'block' => 
  array (
    'module' => 'block',
    'name' => '碎片',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'collection' => 
  array (
    'module' => 'collection',
    'name' => '采集模块',
    'url' => 'collection',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'dbsource' => 
  array (
    'module' => 'dbsource',
    'name' => '数据源',
    'url' => '',
    'iscore' => '1',
    'version' => '',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'template' => 
  array (
    'module' => 'template',
    'name' => '模板风格',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'release' => 
  array (
    'module' => 'release',
    'name' => '发布点',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'comment' => 
  array (
    'module' => 'comment',
    'name' => '评论',
    'url' => 'comment/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '评论',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2017-01-05',
    'updatedate' => '2017-01-05',
  ),
  'link' => 
  array (
    'module' => 'link',
    'name' => '友情链接',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'0\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'poster' => 
  array (
    'module' => 'poster',
    'name' => '广告模块',
    'url' => 'poster/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '广告模块',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2017-01-05',
    'updatedate' => '2017-01-05',
  ),
  'formguide' => 
  array (
    'module' => 'formguide',
    'name' => '表单向导',
    'url' => 'formguide/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'formguide',
    'setting' => 'array (
  \'allowmultisubmit\' => \'1\',
  \'interval\' => \'30\',
  \'allowunreg\' => \'0\',
  \'mailmessage\' => \'用户向我们提交了表单数据，赶快去看看吧。\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-20',
    'updatedate' => '2010-10-20',
  ),
  'chat' => 
  array (
    'module' => 'chat',
    'name' => '聊天',
    'url' => 'chat/',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2019-04-24',
    'updatedate' => '2019-04-24',
  ),
);
?>